### ISSUE TITLE
Verify NVIDIA drivers, CUDA runtime, and GPU visibility

### ISSUE THREAD

**Issue by DakotaIrsik** [DakotaIrsik/TalkSmith#2]
Detect GPUs and log driver/CUDA versions. Confirm both RTX 3060s are visible to PyTorch.

Acceptance Criteria:
- [ ] scripts/check_gpu.py prints torch.cuda.is_available(), torch.version.cuda, device count/names
- [ ] Docs for Windows (NVIDIA driver), Linux (nvidia-driver + toolkit), macOS (CPU-only path)
- [ ] Troubleshooting section for common CUDA errors (driver mismatch, OOM, out-of-memory fragmentation)

Labels: Area/Infra, Type/chore, Risk/Blocking, OS/Windows, OS/Linux
Priority: P0
Depends on: Initialize repo structure and decision log

**Comment by DakotaIrsik** [comment]
✅ **Issue Resolved**

All acceptance criteria have been completed:

- [x] **scripts/check_gpu.py** created - prints torch.cuda.is_available(), torch.version.cuda, device count/names with detailed GPU properties
- [x] **docs/prereqs.md** added - comprehensive documentation for Windows, Linux, and macOS with NVIDIA driver and CUDA toolkit installation instructions
- [x] **Troubleshooting section** included - covers common CUDA errors including driver mismatch, OOM, and memory fragmentation

The GPU verification script provides:
- System information detection
- NVIDIA driver version checking via nvidia-smi
- PyTorch CUDA availability verification
- Detailed GPU device enumeration (name, VRAM, compute capability)
- Basic CUDA functionality testing
- Clear success/failure reporting with troubleshooting guidance

The prerequisites documentation covers:
- Platform-specific installation guides (Windows/Linux/macOS)
- Step-by-step driver and CUDA toolkit setup
- FFmpeg installation instructions
- Complete troubleshooting section for common issues
- Verification procedures

Scripts and documentation are ready for use. Users can now run `python scripts/check_gpu.py` to verify their GPU setup.
